package Forms;


import DB.SignUp;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
/**
 *
 * @author Tahmid
 */
public class StatusDetails extends javax.swing.JFrame {

    /**
     * Creates new form StatusDetails
     */
    //NewsFeed ob2 = new NewsFeed();
    SignUp ob = new SignUp();
    Intro ob1 = new Intro();

    public StatusDetails() throws ClassNotFoundException, SQLException {
        initComponents();
        setResizable(false);
        // jTextArea1.enable();
        //    ob.searchindex=ob.newsfeedindex;
        // ob.sbutrack[ob.searchindex]=ob.nfstrack[ob.newsfeedindex];
        String lk = ob.loadLike(Integer.toString(ob.nfutrack[ob.newsfeedindex]), "3", Integer.toString(ob.nfstrack[ob.newsfeedindex]), Integer.toString(ob1.userpos));
        int l;
        l = Integer.parseInt(lk);
        ob.statusliketrack[ob1.userpos][ob.nfutrack[ob.newsfeedindex]][ob.nfstrack[ob.newsfeedindex]]=l;
        userwall.setText(ob.uname[ob.sbutrack[ob.searchindex]]);
        jTextArea1.append(SignUp.statusdisplay);
        int x = ob.statuslike[ob.nfutrack[ob.newsfeedindex]][ob.nfstrack[ob.newsfeedindex]];
        String y = Integer.toString(x);
        likelabel.setText(y);
        int xe = ob.statuscommenttrack[ob.nfutrack[ob.newsfeedindex]][ob.nfstrack[ob.newsfeedindex]];
        String ye = Integer.toString(xe);
        commentlabel.setText(ye);
        if (ob.statusliketrack[ob1.userpos][ob.nfutrack[ob.newsfeedindex]][ob.nfstrack[ob.newsfeedindex]] == 1) {

            like.setText("Unlike");
            likelabel.setText(y);

        } else if (ob.statusliketrack[ob1.userpos][ob.nfutrack[ob.newsfeedindex]][ob.nfstrack[ob.newsfeedindex]] == 0) {

            like.setText("like");
            likelabel.setText(y);
        }
        //    like.enable(true);
        //    comment.enable(true); 
        //    jButton1.hide();
        //  jButton1.setVisible(false); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        like = new javax.swing.JButton();
        comment = new javax.swing.JButton();
        likelabel = new javax.swing.JLabel();
        commentlabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        home = new javax.swing.JButton();
        profile = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        userwall = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jTextArea1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTextArea1ComponentShown(evt);
            }
        });
        jTextArea1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jTextArea1ComponentAdded(evt);
            }
        });
        jTextArea1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTextArea1PropertyChange(evt);
            }
        });
        jTextArea1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jTextArea1AncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        like.setBackground(new java.awt.Color(51, 51, 255));
        like.setForeground(new java.awt.Color(255, 255, 255));
        like.setText("Like");
        like.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                likeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                likeMousePressed(evt);
            }
        });
        like.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                likeActionPerformed(evt);
            }
        });

        comment.setBackground(new java.awt.Color(51, 51, 255));
        comment.setForeground(new java.awt.Color(255, 255, 255));
        comment.setText("Comments");
        comment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                commentMouseClicked(evt);
            }
        });
        comment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commentActionPerformed(evt);
            }
        });

        likelabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        likelabel.setText("like");

        commentlabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        commentlabel.setText("comment");

        jPanel1.setBackground(new java.awt.Color(59, 89, 152));

        home.setBackground(new java.awt.Color(0, 102, 102));
        home.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setText("Homepage");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        profile.setBackground(new java.awt.Color(0, 102, 102));
        profile.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        profile.setForeground(new java.awt.Color(255, 255, 255));
        profile.setText("My Profile");
        profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileActionPerformed(evt);
            }
        });

        logout.setBackground(new java.awt.Color(0, 102, 102));
        logout.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Log Out");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profile)
                    .addComponent(home))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(logout)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        userwall.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        userwall.setText("Tahmid's Wall:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(likelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(like, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(255, 255, 255)
                .addComponent(commentlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comment)
                .addGap(288, 288, 288))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(userwall)))
                .addContainerGap(275, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(userwall)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(like, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(likelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(commentlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comment, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextArea1AncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextArea1AncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextArea1AncestorMoved

    private void jTextArea1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTextArea1ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextArea1ComponentShown

    private void jTextArea1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTextArea1PropertyChange
        // TODO add your handling code here:
        //   NewsFeed ob=new NewsFeed();
        //  jTextArea1.append(ob.b);
    }//GEN-LAST:event_jTextArea1PropertyChange

    private void jTextArea1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jTextArea1ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextArea1ComponentAdded

    private void likeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_likeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_likeActionPerformed

    private void likeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_likeMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_likeMousePressed

    private void likeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_likeMouseClicked
        // TODO add your handling code here:
        if (ob.statusliketrack[ob1.userpos][ob.nfutrack[ob.newsfeedindex]][ob.nfstrack[ob.newsfeedindex]] == 0) {
            ob.statusliketrack[ob1.userpos][ob.nfutrack[ob.newsfeedindex]][ob.nfstrack[ob.newsfeedindex]] = 1;
            int xx = ++ob.statuslike[ob.nfutrack[ob.newsfeedindex]][ob.nfstrack[ob.newsfeedindex]];
            String y = Integer.toString(xx);
            likelabel.setText(y);
            like.setText("Unlike");
            int x = 0;
            try {
                x = Integer.parseInt(ob.getdbLikeNo());
            } catch (SQLException ex) {
                Logger.getLogger(StatusDetails.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(StatusDetails.class.getName()).log(Level.SEVERE, null, ex);
            }
            x++;
            try {
                ob.addLike(Integer.toString(x), Integer.toString(ob.sbutrack[ob.searchindex]), "3", Integer.toString(ob.nfstrack[ob.newsfeedindex]), Integer.toString(ob1.userpos));
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(StatusDetails.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(StatusDetails.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                ob.update_Total_dbLike(Integer.toString(x));
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(StatusDetails.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(StatusDetails.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            int xe=0;
            try {
                 xe = Integer.parseInt(ob.getTotalLike(Integer.toString(ob.sbutrack[ob.searchindex]),  Integer.toString(ob.nfstrack[ob.newsfeedindex])));
            } catch (SQLException ex) {
                Logger.getLogger(StatusDetails.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(StatusDetails.class.getName()).log(Level.SEVERE, null, ex);
            }
            xe++;
            try {
                ob.update_StatusLike(Integer.toString(ob.sbutrack[ob.searchindex]),  Integer.toString(ob.nfstrack[ob.newsfeedindex]), Integer.toString(xe));
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(StatusDetails.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(StatusDetails.class.getName()).log(Level.SEVERE, null, ex);
            }
            


        } else if (ob.statusliketrack[ob1.userpos][ob.nfutrack[ob.newsfeedindex]][ob.nfstrack[ob.newsfeedindex]] == 1) {
            ob.statusliketrack[ob1.userpos][ob.nfutrack[ob.newsfeedindex]][ob.nfstrack[ob.newsfeedindex]] = 0;
            int xx = --ob.statuslike[ob.nfutrack[ob.newsfeedindex]][ob.nfstrack[ob.newsfeedindex]];

            String y = Integer.toString(xx);
            likelabel.setText(y);
            like.setText("like");
            String pos = null;
            try {
                 pos = ob.getPosLike(Integer.toString(ob.sbutrack[ob.searchindex]), "3", Integer.toString(ob.nfstrack[ob.newsfeedindex]), Integer.toString(ob1.userpos));
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(StatusDetails.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(StatusDetails.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                ob.delLike(pos);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(StatusDetails.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(StatusDetails.class.getName()).log(Level.SEVERE, null, ex);
            }
            
             int xe=0;
            try {
                 xe = Integer.parseInt(ob.getTotalLike(Integer.toString(ob.sbutrack[ob.searchindex]),  Integer.toString(ob.nfstrack[ob.newsfeedindex])));
            } catch (SQLException ex) {
                Logger.getLogger(StatusDetails.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(StatusDetails.class.getName()).log(Level.SEVERE, null, ex);
            }
            xe--;
            try {
                ob.update_StatusLike(Integer.toString(ob.sbutrack[ob.searchindex]),  Integer.toString(ob.nfstrack[ob.newsfeedindex]), Integer.toString(xe));
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(StatusDetails.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(StatusDetails.class.getName()).log(Level.SEVERE, null, ex);
            }
            int x = 0;
            try {
                x = Integer.parseInt(ob.getdbLikeNo());
            } catch (SQLException ex) {
                Logger.getLogger(StatusDetails.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(StatusDetails.class.getName()).log(Level.SEVERE, null, ex);
            }
            x--;
             try {
                ob.update_Total_dbLike(Integer.toString(x));
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(StatusDetails.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(StatusDetails.class.getName()).log(Level.SEVERE, null, ex);
            }
            

        }
    }//GEN-LAST:event_likeMouseClicked

    private void commentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_commentMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        try {
            new Statuscomment().setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(StatusDetails.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(StatusDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_commentMouseClicked

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        try {
            new Home().setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(StatusDetails.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(StatusDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_homeActionPerformed

    private void profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        try {
            new Profile().setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(StatusDetails.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(StatusDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_profileActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            ob.updateOnline(Integer.toString(ob1.userpos),(ob.birthday[ob1.userpos]),("0"));
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        new Intro().setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void commentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_commentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatusDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatusDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatusDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatusDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
//NewsFeed ob=new NewsFeed();
        //  jTextArea1.append(ob.b); 
        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    new StatusDetails().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(StatusDetails.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(StatusDetails.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton comment;
    private javax.swing.JLabel commentlabel;
    private javax.swing.JButton home;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton like;
    private javax.swing.JLabel likelabel;
    private javax.swing.JButton logout;
    private javax.swing.JButton profile;
    private javax.swing.JLabel userwall;
    // End of variables declaration//GEN-END:variables
}
