package Forms;


import DB.SignUp;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tahmid
 */
/*
 *     String day="2",month="3",year="4";
     //   day=(String)jSpinner1.getValue();
     //  day=(String)jSpinner1.getValue();
       int d=((Integer)(jSpinner1.getValue())).intValue();
       day=Integer.toString(d);
        if(d<10)
        {
            day="0"+day;
        }
    //    month=(String) jSpinner2.getValue();
      //    month=(String)jSpinner1.getValue();
       int m=((Integer)(jSpinner2.getValue())).intValue();
       month=Integer.toString(m);
        if(m<10)
        {
           month="0"+month;
        }
       int y=((Integer)(jSpinner3.getValue())).intValue();
       year=Integer.toString(y);
               
        DOB.setText("Date of Birth: "+day+"-"+month+"-"+year);
 */
public class Testingfrnd extends javax.swing.JFrame {

    /**
     * Creates new form ProfileI
     */
     SignUp ob=new SignUp();
    Intro ob1=new Intro();
    public Testingfrnd() {
        initComponents();
        setResizable(false);
        if(ob.frndchecker[ob1.userpos][ob.friendlisttrack]==1&&ob.frndchecker[ob.friendlisttrack][ob1.userpos]==1)
        {
            frndrequest.setText("Remove Friend");
        }
        username.setText("Username: "+ob.uname[ob.friendlisttrack]);
         institute.setText("Institue: "+ob.education_institute[ob.friendlisttrack]);
         sex.setText("Sex: "+ob.sex[ob.friendlisttrack]);
         work.setText("Work: "+ob.working[ob.friendlisttrack]);
         email.setText("Email: "+"N/A");
       
        if(ob.privacy[ob.friendlisttrack][1] == 1)
         institute.setVisible(false);
         if(ob.privacy[ob.friendlisttrack][2] == 1)
         email.setVisible(false);
          if(ob.privacy[ob.friendlisttrack][3] == 1)
         work.setVisible(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Status = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        message = new javax.swing.JButton();
        email = new javax.swing.JLabel();
        work = new javax.swing.JLabel();
        DOB = new javax.swing.JLabel();
        institute = new javax.swing.JLabel();
        sex = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        Friendlist = new javax.swing.JButton();
        Wall = new javax.swing.JButton();
        pinfo = new javax.swing.JLabel();
        frndrequest = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Status.setText("Show Status");
        Status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusActionPerformed(evt);
            }
        });
        getContentPane().add(Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 150, 45));

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 50, 86, -1));

        message.setText("Send Message");
        message.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageActionPerformed(evt);
            }
        });
        getContentPane().add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 429, 152, 45));

        email.setText("Email:");
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 295, 152, 30));

        work.setText("Working at:");
        getContentPane().add(work, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 246, 559, 31));

        DOB.setText("Date Of Birth:");
        getContentPane().add(DOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 339, 190, 37));

        institute.setText("Institute:");
        getContentPane().add(institute, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 148, 549, 37));

        sex.setText("Sex:");
        getContentPane().add(sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 203, 190, 37));

        username.setText("Username:");
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 15, 212, 31));

        Friendlist.setText("Friend List");
        getContentPane().add(Friendlist, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 430, 139, 45));

        Wall.setText("Check Wall");
        Wall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WallActionPerformed(evt);
            }
        });
        getContentPane().add(Wall, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, 146, 45));

        pinfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pinfo.setText("Personal Information:");
        getContentPane().add(pinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 89, 264, 32));

        frndrequest.setText("Send Friend Request");
        frndrequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frndrequestActionPerformed(evt);
            }
        });
        getContentPane().add(frndrequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, 145, 35));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
            this.setVisible(false);
        try {
            new  Home().setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Testingfrnd.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Testingfrnd.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BackActionPerformed

    private void messageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
            new  Message().setVisible(true);
    }//GEN-LAST:event_messageActionPerformed

    private void frndrequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frndrequestActionPerformed
        // TODO add your handling code here:
           // this.setVisible(false);
          //  new  Sendfriendrequest().setVisible(true);
        
        ob.frndchecker[ob1.userpos][ob.friendlisttrack]=0;
        ob.frndchecker[ob.friendlisttrack][ob1.userpos]=0;
        ob.newfrnd[ob.friendlisttrack]--;
        ob.sbutrack[ob.searchindex]=ob.friendlisttrack;
         frndrequest.setText("Send Friend Request");
         this.setVisible(false);
        try {
            new ProfileOthers().setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Testingfrnd.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Testingfrnd.class.getName()).log(Level.SEVERE, null, ex);
        }
           // frndrequest.hide();
            //frndrequest.hide();
            //frndrequest.setVisible(false);
           frndrequest.hide();
    }//GEN-LAST:event_frndrequestActionPerformed

    private void WallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WallActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        try {
            new Otherswall().setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Testingfrnd.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Testingfrnd.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_WallActionPerformed

    private void StatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfileOthers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfileOthers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfileOthers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfileOthers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ProfileOthers().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Testingfrnd.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Testingfrnd.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel DOB;
    private javax.swing.JButton Friendlist;
    private javax.swing.JButton Status;
    private javax.swing.JButton Wall;
    private javax.swing.JLabel email;
    private javax.swing.JButton frndrequest;
    private javax.swing.JLabel institute;
    private javax.swing.JButton message;
    private javax.swing.JLabel pinfo;
    private javax.swing.JLabel sex;
    private javax.swing.JLabel username;
    private javax.swing.JLabel work;
    // End of variables declaration//GEN-END:variables
}
