/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tahmid
 */
public class StatusDetails extends javax.swing.JFrame {

    /**
     * Creates new form StatusDetails
     */
    public StatusDetails() {
        initComponents();
        jTextArea1.enable();
        jTextArea1.append(ob1.b);
       int x = ob.statuslike[ob.nfutrack[ob.newsfeedindex]][ob.nfstrack[ob.newsfeedindex]];

            String y = Integer.toString(x);
            likelabel.setText(y);
      if (ob.statusliketrack[ob2.userpos][ob.nfutrack[ob.newsfeedindex]][ob.nfstrack[ob.newsfeedindex]] == 1) {

            like.setText("Unlike");
           likelabel.setText(y);
            
        } else if (ob.statusliketrack[ob2.userpos][ob.nfutrack[ob.newsfeedindex]][ob.nfstrack[ob.newsfeedindex]] == 0) {

            like.setText("like");
           likelabel.setText(y);
        }
        like.enable(true);
        comment.enable(true); 
        //    jButton1.hide();
        jButton1.setVisible(false);
    }
    NewsFeed ob1 = new NewsFeed();
    SignUp ob = new SignUp();
    Intro ob2 = new Intro();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        like = new javax.swing.JButton();
        comment = new javax.swing.JButton();
        likelabel = new javax.swing.JLabel();
        commentlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jTextArea1.setEnabled(false);
        jTextArea1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTextArea1ComponentShown(evt);
            }
        });
        jTextArea1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jTextArea1ComponentAdded(evt);
            }
        });
        jTextArea1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTextArea1PropertyChange(evt);
            }
        });
        jTextArea1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jTextArea1AncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Show The Status");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        like.setText("Like");
        like.setEnabled(false);
        like.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                likeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                likeMousePressed(evt);
            }
        });
        like.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                likeActionPerformed(evt);
            }
        });

        comment.setText("Comments");
        comment.setEnabled(false);
        comment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                commentMouseClicked(evt);
            }
        });

        likelabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        commentlabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1075, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addComponent(likelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(like, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(195, 195, 195)
                        .addComponent(commentlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comment))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(425, 425, 425)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(commentlabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comment)
                        .addComponent(like)
                        .addComponent(likelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addComponent(jButton1)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextArea1AncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextArea1AncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextArea1AncestorMoved

    private void jTextArea1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTextArea1ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextArea1ComponentShown

    private void jTextArea1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTextArea1PropertyChange
        // TODO add your handling code here:
        //   NewsFeed ob=new NewsFeed();
        //  jTextArea1.append(ob.b);
    }//GEN-LAST:event_jTextArea1PropertyChange

    private void jTextArea1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jTextArea1ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextArea1ComponentAdded

    private void likeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_likeActionPerformed
        // TODO add your handling code here:

        

    }//GEN-LAST:event_likeActionPerformed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButton1MousePressed

    private void likeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_likeMousePressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_likeMousePressed

    private void likeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_likeMouseClicked
        // TODO add your handling code here:
          if (ob.statusliketrack[ob2.userpos][ob.nfutrack[ob.newsfeedindex]][ob.nfstrack[ob.newsfeedindex]] == 0) {
            ob.statusliketrack[ob2.userpos][ob.nfutrack[ob.newsfeedindex]][ob.nfstrack[ob.newsfeedindex]] = 1;
             int x = ++ob.statuslike[ob.nfutrack[ob.newsfeedindex]][ob.nfstrack[ob.newsfeedindex]];

            String y = Integer.toString(x);
            likelabel.setText(y);
            like.setText("Unlike");
            
           
        } else if (ob.statusliketrack[ob2.userpos][ob.nfutrack[ob.newsfeedindex]][ob.nfstrack[ob.newsfeedindex]] == 1) {
            ob.statusliketrack[ob2.userpos][ob.nfutrack[ob.newsfeedindex]][ob.nfstrack[ob.newsfeedindex]] = 0;
             int x = --ob.statuslike[ob.nfutrack[ob.newsfeedindex]][ob.nfstrack[ob.newsfeedindex]];

            String y = Integer.toString(x);
            likelabel.setText(y);
            like.setText("like");
           
        }
    }//GEN-LAST:event_likeMouseClicked

    private void commentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_commentMouseClicked
        // TODO add your handling code here:
         this.setVisible(false);
         new Statuscomment().setVisible(true);
    }//GEN-LAST:event_commentMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatusDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatusDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatusDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatusDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
//NewsFeed ob=new NewsFeed();
        //  jTextArea1.append(ob.b); 
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StatusDetails().setVisible(true);

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton comment;
    private javax.swing.JLabel commentlabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton like;
    private javax.swing.JLabel likelabel;
    // End of variables declaration//GEN-END:variables
}
